version: "3"

services:
    backend:
        build:
            context: ./
            dockerfile: dockerfiles/app/Dockerfile
        volumes:
            - "./backend:/var/www/html"
        ports:
            - "8082:80"
    frontend:
        build:
            context: ./
            dockerfile: dockerfiles/app/Dockerfile
        volumes:
            - "./frontend:/var/www/html"
        ports:
            - "8083:80"
    mysql:
        build:
            context: ./
            dockerfile: dockerfiles/mysql/Dockerfile
        volumes:
            - "mysql-data:/var/lib/mysql"
        environment:
            - MYSQL_ROOT_PASSWORD=secret
            - MYSQL_DATABASE=db_name
        ports:
            - "33069:3306"

volumes:
    mysql-data:
        driver: "local"
